### ISSUE TITLE
Push updated README to Elm packages

### ISSUE THREAD

**Issue by j-maas** [wittjosiah/elm-ordered-dict#5]
The current heading in the README does not appear on the [package's documentation](https://package.elm-lang.org/packages/wittjosiah/elm-ordered-dict/latest/). Please consider pushing a new patch version of the library, 1.0.2, to update the README there.

**Comment by wittjosiah** [comment]
This should be resolved now!

**Comment by j-maas** [comment]
Awesome, thank you! 😊
